### ISSUE TITLE
Error running npm start with proxy in package.json

### ISSUE THREAD

**Issue by sb1975** [rapPayne/react_in_3_weeks#3]
Getting error when adding proxy in package.json
`"proxy": "http://localhost:3008",`

Error : 

```
$ npm start
Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options.allowedHosts[0] should be a non-empty string.
```

Resolution : 
export DANGEROUSLY_DISABLE_HOST_CHECK=true

Ref : https://github.com/facebook/create-react-app/issues/12304

**Comment by rapPayne** [comment]
Make sure your proxy line is at the top level. In other words, it can't be a sub-node under `scripts` or `dependencies` or `devDependencies` or whatever else.

**Comment by drinchev** [comment]
Try changing 

```
  "proxy": "http://localhost:3008",
```

to

```
  "proxy": "http://127.0.0.1:3008/",
```

Seems to fix it for me.
